version: "3.8"

services:
  api_app:
    build: ./api  # Ensure your FastAPI app is inside the 'api' folder
    ports:
      - "8000:8000"  # Expose FastAPI app on port 8000
    environment:
      - DATABASE_URL=mysql://root:Spooks##2023@mysql:3306/LED_db
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Spooks##2023
      MYSQL_DATABASE: LED_db
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"  # Expose phpMyAdmin on port 8080
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
